name: KyarasuCI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend
      - name: Install backend
        run: |
          cd Backend
          npm install

      - name: Test backend
        run: |
          cd Backend

      # Frontend?
      - name: Install frontend
        run: |
          cd Frontend
          npm install

      - name: Test frontend
        run: |
          cd Frontend
